site_name: PYTDXEXT
site_description: 基于 Mootdx以及Mootdx的源码扩展(由于pytdx作者已经不再维护,本项目主要目的是持续维护pytdx源码),考虑到mootdx对pytdx的二次封装更好用,所以本项目的核心入口接口全部使用mootdx,而pytdx的核心接口将不直接开放出来。

theme: readthedocs

nav:
  - 快速开始:
    - 项目概述: index.md
    - 安装说明: setup.md
    - 快速上手: quick.md
    - 修改日志: chlog.md

    - 行情接口:
      - 标准行情: api/quote1.md
      - 扩展行情: api/quote2.md
      - 数据读取: api/reader.md
      - 财务数据: api/affair.md
      - 财务对照: api/fields.md
      - 辅助函数: api/extras.md

    - 命令行工具:
      - 线路测试: cli/bestip.md
      - 离线数据: cli/reader.md
      - 行情数据: cli/quotes.md
      - 财务数据: cli/affair.md
      - 批量下载: cli/bundle.md
